import React from "react";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Card, Loader, FormField } from "../components";
import {
	fetchPosts,
	setSearchText,
	setSearchTimeout,
	setSearchedResults,
} from "../features/homePage/homePageSlice";

const RenderCards = ({ data, title }) => {
	if (data?.length > 0) {
		return data.map((post) => <Card key={post._id} {...post} />);
	}
	return (
		<h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
	);
};

const Home = () => {
	const dispatch = useDispatch();
	const { allPosts, loading, searchText, searchedResults, searchTimeout } =
		useSelector((store) => store.homePage);

	useEffect(() => {
		dispatch(fetchPosts());
	}, []);

	const handleSearchChange = (e) => {
		clearTimeout(searchTimeout);
		dispatch(setSearchText(e.target.value));
		dispatch(
			setSearchTimeout(
				setTimeout(() => {
					const searchResults = allPosts.filter((post) => {
						return (
							post.name.toLowerCase().includes(searchText.toLowerCase()) ||
							post.prompt.toLowerCase().includes(searchText.toLowerCase())
						);
					});
					dispatch(setSearchedResults(searchResults));
				}, 500)
			)
		);
	};
	return (
		<section className="max-w-7xl mx-auto">
			<div>
				<h1 className="font-extrabold text-[#222328] text-[32px]">
					The Community showcase
				</h1>
				<p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
					Browse through a collection of imaginitive and visually stunning
					images generated by SUM-E AI
				</p>
			</div>

			<div className="mt-16">
				<FormField
					type="text"
					name="text"
					value={searchText}
					labelName="Search Posts by Name or Prompt"
					placeholder="Search Posts..."
					isSurpriseMe={false}
					handleChange={handleSearchChange}
				/>
			</div>

			<div className="mt-10">
				{loading ? (
					<div className="flex justify-center items-center">
						<Loader />
					</div>
				) : (
					<>
						{searchText && (
							<h2 className="font-medium text-[#666e75] text-xl mb-3">
								Showing results for{" "}
								<span className="text=[#222328]">{searchText}</span>
							</h2>
						)}

						<div className="grid lg:grid-cols-4 xs:grid-cols-2 sm:grid-cols-3 grid-cols-1 gap-3">
							{searchText ? (
								<RenderCards data={searchedResults} title="No Search results" />
							) : (
								<RenderCards data={allPosts} title="No Posts" />
							)}
						</div>
					</>
				)}
			</div>
		</section>
	);
};

export default Home;
